// Code generated by protoc-gen-go. DO NOT EDIT.
// source: natter.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 0x01
type RegisterRequest struct {
	Source               string   `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39129eec69c18084, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

// 0x02
type RegisterResponse struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39129eec69c18084, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// 0x03
type ForwardRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	SourceAddr           string   `protobuf:"bytes,3,opt,name=SourceAddr,proto3" json:"SourceAddr,omitempty"`
	Target               string   `protobuf:"bytes,4,opt,name=Target,proto3" json:"Target,omitempty"`
	TargetAddr           string   `protobuf:"bytes,5,opt,name=TargetAddr,proto3" json:"TargetAddr,omitempty"`
	TargetForwardAddr    string   `protobuf:"bytes,6,opt,name=TargetForwardAddr,proto3" json:"TargetForwardAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardRequest) Reset()         { *m = ForwardRequest{} }
func (m *ForwardRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardRequest) ProtoMessage()    {}
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39129eec69c18084, []int{2}
}

func (m *ForwardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardRequest.Unmarshal(m, b)
}
func (m *ForwardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardRequest.Marshal(b, m, deterministic)
}
func (m *ForwardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardRequest.Merge(m, src)
}
func (m *ForwardRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardRequest.Size(m)
}
func (m *ForwardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardRequest proto.InternalMessageInfo

func (m *ForwardRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ForwardRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ForwardRequest) GetSourceAddr() string {
	if m != nil {
		return m.SourceAddr
	}
	return ""
}

func (m *ForwardRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ForwardRequest) GetTargetAddr() string {
	if m != nil {
		return m.TargetAddr
	}
	return ""
}

func (m *ForwardRequest) GetTargetForwardAddr() string {
	if m != nil {
		return m.TargetForwardAddr
	}
	return ""
}

// 0x04
type ForwardResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`
	SourceAddr           string   `protobuf:"bytes,4,opt,name=SourceAddr,proto3" json:"SourceAddr,omitempty"`
	Target               string   `protobuf:"bytes,5,opt,name=Target,proto3" json:"Target,omitempty"`
	TargetAddr           string   `protobuf:"bytes,6,opt,name=TargetAddr,proto3" json:"TargetAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardResponse) Reset()         { *m = ForwardResponse{} }
func (m *ForwardResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardResponse) ProtoMessage()    {}
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39129eec69c18084, []int{3}
}

func (m *ForwardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardResponse.Unmarshal(m, b)
}
func (m *ForwardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardResponse.Marshal(b, m, deterministic)
}
func (m *ForwardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardResponse.Merge(m, src)
}
func (m *ForwardResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardResponse.Size(m)
}
func (m *ForwardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardResponse proto.InternalMessageInfo

func (m *ForwardResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ForwardResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ForwardResponse) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ForwardResponse) GetSourceAddr() string {
	if m != nil {
		return m.SourceAddr
	}
	return ""
}

func (m *ForwardResponse) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ForwardResponse) GetTargetAddr() string {
	if m != nil {
		return m.TargetAddr
	}
	return ""
}

// 0x05
type KeepaliveRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Rand                 int32    `protobuf:"varint,2,opt,name=rand,proto3" json:"rand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepaliveRequest) Reset()         { *m = KeepaliveRequest{} }
func (m *KeepaliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepaliveRequest) ProtoMessage()    {}
func (*KeepaliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39129eec69c18084, []int{4}
}

func (m *KeepaliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepaliveRequest.Unmarshal(m, b)
}
func (m *KeepaliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepaliveRequest.Marshal(b, m, deterministic)
}
func (m *KeepaliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepaliveRequest.Merge(m, src)
}
func (m *KeepaliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepaliveRequest.Size(m)
}
func (m *KeepaliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepaliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepaliveRequest proto.InternalMessageInfo

func (m *KeepaliveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *KeepaliveRequest) GetRand() int32 {
	if m != nil {
		return m.Rand
	}
	return 0
}

// 0x06
type KeepaliveResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Rand                 int32    `protobuf:"varint,2,opt,name=rand,proto3" json:"rand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepaliveResponse) Reset()         { *m = KeepaliveResponse{} }
func (m *KeepaliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepaliveResponse) ProtoMessage()    {}
func (*KeepaliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39129eec69c18084, []int{5}
}

func (m *KeepaliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepaliveResponse.Unmarshal(m, b)
}
func (m *KeepaliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepaliveResponse.Marshal(b, m, deterministic)
}
func (m *KeepaliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepaliveResponse.Merge(m, src)
}
func (m *KeepaliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepaliveResponse.Size(m)
}
func (m *KeepaliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepaliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepaliveResponse proto.InternalMessageInfo

func (m *KeepaliveResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *KeepaliveResponse) GetRand() int32 {
	if m != nil {
		return m.Rand
	}
	return 0
}

// 0x07
type DataMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataMessage) Reset()         { *m = DataMessage{} }
func (m *DataMessage) String() string { return proto.CompactTextString(m) }
func (*DataMessage) ProtoMessage()    {}
func (*DataMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_39129eec69c18084, []int{6}
}

func (m *DataMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMessage.Unmarshal(m, b)
}
func (m *DataMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMessage.Marshal(b, m, deterministic)
}
func (m *DataMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMessage.Merge(m, src)
}
func (m *DataMessage) XXX_Size() int {
	return xxx_messageInfo_DataMessage.Size(m)
}
func (m *DataMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DataMessage proto.InternalMessageInfo

func (m *DataMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "main.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "main.RegisterResponse")
	proto.RegisterType((*ForwardRequest)(nil), "main.ForwardRequest")
	proto.RegisterType((*ForwardResponse)(nil), "main.ForwardResponse")
	proto.RegisterType((*KeepaliveRequest)(nil), "main.KeepaliveRequest")
	proto.RegisterType((*KeepaliveResponse)(nil), "main.KeepaliveResponse")
	proto.RegisterType((*DataMessage)(nil), "main.DataMessage")
}

func init() { proto.RegisterFile("natter.proto", fileDescriptor_39129eec69c18084) }

var fileDescriptor_39129eec69c18084 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcb, 0x4a, 0xc4, 0x30,
	0x14, 0x86, 0x69, 0xa7, 0xad, 0x7a, 0x1c, 0xe6, 0x92, 0x85, 0x74, 0x25, 0x92, 0x85, 0x28, 0x88,
	0x20, 0x82, 0xae, 0x05, 0x11, 0x06, 0x71, 0x93, 0xf1, 0x05, 0x62, 0x73, 0x28, 0x05, 0x6d, 0x6b,
	0x92, 0xea, 0x43, 0xf9, 0x0e, 0x3e, 0x9b, 0xf4, 0x24, 0xe3, 0x84, 0xb9, 0x74, 0xf7, 0x9f, 0xe4,
	0xff, 0x92, 0x7c, 0xa5, 0x30, 0xae, 0xa5, 0xb5, 0xa8, 0xaf, 0x5b, 0xdd, 0xd8, 0x86, 0x25, 0x1f,
	0xb2, 0xaa, 0xf9, 0x25, 0x4c, 0x05, 0x96, 0x95, 0xb1, 0xa8, 0x05, 0x7e, 0x76, 0x68, 0x2c, 0x3b,
	0x81, 0x6c, 0xd9, 0x74, 0xba, 0xc0, 0x3c, 0x3a, 0x8b, 0x2e, 0x8e, 0x84, 0x9f, 0xf8, 0x39, 0xcc,
	0xd6, 0x55, 0xd3, 0x36, 0xb5, 0x41, 0xc6, 0x20, 0x79, 0x50, 0x4a, 0xfb, 0x26, 0x65, 0xfe, 0x1b,
	0xc1, 0xe4, 0xa9, 0xd1, 0xdf, 0x52, 0xab, 0xd5, 0x91, 0x13, 0x88, 0x17, 0xca, 0x97, 0xe2, 0x85,
	0x0a, 0xae, 0x88, 0xc3, 0x2b, 0xd8, 0x29, 0x80, 0x4b, 0x74, 0xe8, 0x88, 0xf6, 0x82, 0x95, 0x9e,
	0x7b, 0x95, 0xba, 0x44, 0x9b, 0x27, 0x8e, 0x73, 0x53, 0xcf, 0xb9, 0x44, 0x5c, 0xea, 0xb8, 0xf5,
	0x0a, 0xbb, 0x82, 0xb9, 0x9b, 0xfc, 0xbb, 0xa8, 0x96, 0x51, 0x6d, 0x7b, 0x83, 0xff, 0x44, 0x30,
	0xfd, 0x17, 0xf0, 0xa2, 0x9b, 0x06, 0x39, 0x1c, 0x2c, 0xbb, 0xa2, 0x40, 0x63, 0x48, 0xe1, 0x50,
	0xac, 0xc6, 0xc0, 0x6d, 0x34, 0xe0, 0x96, 0x0c, 0xb8, 0xa5, 0x03, 0x6e, 0xd9, 0xa6, 0x1b, 0xbf,
	0x83, 0xd9, 0x33, 0x62, 0x2b, 0xdf, 0xab, 0x2f, 0xdc, 0xf7, 0xbd, 0x19, 0x24, 0x5a, 0xd6, 0x8a,
	0x9e, 0x9a, 0x0a, 0xca, 0xfc, 0x1e, 0xe6, 0x01, 0xb7, 0x47, 0x73, 0x17, 0x78, 0x03, 0xc7, 0x8f,
	0xd2, 0xca, 0x17, 0x34, 0x46, 0x96, 0x3b, 0x91, 0x7e, 0x9b, 0x90, 0xb1, 0xa0, 0xfc, 0x96, 0xd1,
	0x2f, 0x77, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x30, 0xbd, 0xd0, 0x82, 0x02, 0x00, 0x00,
}
