// Code generated by protoc-gen-go. DO NOT EDIT.
// source: natter.proto

package natter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 0x01
type RegisterRequest struct {
	Source               string   `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39129eec69c18084, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

// 0x02
type RegisterResponse struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39129eec69c18084, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// 0x03
type ForwardRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	SourceAddr           string   `protobuf:"bytes,3,opt,name=SourceAddr,proto3" json:"SourceAddr,omitempty"`
	Target               string   `protobuf:"bytes,4,opt,name=Target,proto3" json:"Target,omitempty"`
	TargetAddr           string   `protobuf:"bytes,5,opt,name=TargetAddr,proto3" json:"TargetAddr,omitempty"`
	TargetForwardAddr    string   `protobuf:"bytes,6,opt,name=TargetForwardAddr,proto3" json:"TargetForwardAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardRequest) Reset()         { *m = ForwardRequest{} }
func (m *ForwardRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardRequest) ProtoMessage()    {}
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39129eec69c18084, []int{2}
}

func (m *ForwardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardRequest.Unmarshal(m, b)
}
func (m *ForwardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardRequest.Marshal(b, m, deterministic)
}
func (m *ForwardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardRequest.Merge(m, src)
}
func (m *ForwardRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardRequest.Size(m)
}
func (m *ForwardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardRequest proto.InternalMessageInfo

func (m *ForwardRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ForwardRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ForwardRequest) GetSourceAddr() string {
	if m != nil {
		return m.SourceAddr
	}
	return ""
}

func (m *ForwardRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ForwardRequest) GetTargetAddr() string {
	if m != nil {
		return m.TargetAddr
	}
	return ""
}

func (m *ForwardRequest) GetTargetForwardAddr() string {
	if m != nil {
		return m.TargetForwardAddr
	}
	return ""
}

// 0x04
type ForwardResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`
	SourceAddr           string   `protobuf:"bytes,4,opt,name=SourceAddr,proto3" json:"SourceAddr,omitempty"`
	Target               string   `protobuf:"bytes,5,opt,name=Target,proto3" json:"Target,omitempty"`
	TargetAddr           string   `protobuf:"bytes,6,opt,name=TargetAddr,proto3" json:"TargetAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardResponse) Reset()         { *m = ForwardResponse{} }
func (m *ForwardResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardResponse) ProtoMessage()    {}
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39129eec69c18084, []int{3}
}

func (m *ForwardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardResponse.Unmarshal(m, b)
}
func (m *ForwardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardResponse.Marshal(b, m, deterministic)
}
func (m *ForwardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardResponse.Merge(m, src)
}
func (m *ForwardResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardResponse.Size(m)
}
func (m *ForwardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardResponse proto.InternalMessageInfo

func (m *ForwardResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ForwardResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ForwardResponse) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ForwardResponse) GetSourceAddr() string {
	if m != nil {
		return m.SourceAddr
	}
	return ""
}

func (m *ForwardResponse) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ForwardResponse) GetTargetAddr() string {
	if m != nil {
		return m.TargetAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "natter.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "natter.RegisterResponse")
	proto.RegisterType((*ForwardRequest)(nil), "natter.ForwardRequest")
	proto.RegisterType((*ForwardResponse)(nil), "natter.ForwardResponse")
}

func init() { proto.RegisterFile("natter.proto", fileDescriptor_39129eec69c18084) }

var fileDescriptor_39129eec69c18084 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xb7, 0x1b, 0x75, 0x90, 0x5d, 0xcd, 0x41, 0x7a, 0x12, 0xc9, 0x41, 0x14, 0xc4,
	0x8b, 0x4f, 0xe0, 0x45, 0xd8, 0x6b, 0xd6, 0x17, 0xa8, 0xcd, 0x50, 0xbc, 0x34, 0x75, 0x92, 0xe2,
	0x43, 0xf9, 0x0e, 0x3e, 0x9b, 0x74, 0x92, 0xda, 0xd0, 0x85, 0xde, 0xe6, 0x9f, 0xf9, 0xff, 0x99,
	0x7c, 0x04, 0x2e, 0xbb, 0x3a, 0x04, 0xa4, 0xe7, 0x9e, 0x5c, 0x70, 0x4a, 0x46, 0xa5, 0x1f, 0x61,
	0x6f, 0xb0, 0xfd, 0xf4, 0x01, 0xc9, 0xe0, 0xd7, 0x80, 0x3e, 0xa8, 0x1b, 0x90, 0x47, 0x37, 0x50,
	0x83, 0x95, 0xb8, 0x13, 0x0f, 0x17, 0x26, 0x29, 0x7d, 0x0f, 0x57, 0xb3, 0xd5, 0xf7, 0xae, 0xf3,
	0xa8, 0x14, 0x94, 0xaf, 0xd6, 0x52, 0x72, 0x72, 0xad, 0x7f, 0x05, 0xec, 0xde, 0x1c, 0x7d, 0xd7,
	0x64, 0xa7, 0x95, 0x3b, 0x28, 0x0e, 0x36, 0x99, 0x8a, 0x83, 0xcd, 0x4e, 0x14, 0xf9, 0x09, 0x75,
	0x0b, 0x10, 0x2b, 0x5e, 0xba, 0xe1, 0x59, 0xd6, 0x19, 0x73, 0xef, 0x35, 0xb5, 0x18, 0xaa, 0x32,
	0xe6, 0xa2, 0x1a, 0x73, 0xb1, 0xe2, 0xdc, 0x36, 0xe6, 0xe6, 0x8e, 0x7a, 0x82, 0xeb, 0xa8, 0xd2,
	0xbb, 0xd8, 0x26, 0xd9, 0x76, 0x3a, 0xd0, 0x3f, 0x02, 0xf6, 0xff, 0x00, 0x09, 0x74, 0x49, 0x50,
	0xc1, 0xd9, 0x71, 0x68, 0x1a, 0xf4, 0x9e, 0x11, 0xce, 0xcd, 0x24, 0x33, 0xb6, 0xcd, 0x0a, 0x5b,
	0xb9, 0xc2, 0xb6, 0x5d, 0x61, 0x93, 0x4b, 0xb6, 0x0f, 0xc9, 0x1f, 0xfa, 0xf2, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x07, 0xaf, 0xc6, 0xc8, 0xe0, 0x01, 0x00, 0x00,
}
