// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/natter.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 0x01
type CheckinRequest struct {
	Source               string   `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckinRequest) Reset()         { *m = CheckinRequest{} }
func (m *CheckinRequest) String() string { return proto.CompactTextString(m) }
func (*CheckinRequest) ProtoMessage()    {}
func (*CheckinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0895f35a7d2a8f3, []int{0}
}

func (m *CheckinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckinRequest.Unmarshal(m, b)
}
func (m *CheckinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckinRequest.Marshal(b, m, deterministic)
}
func (m *CheckinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckinRequest.Merge(m, src)
}
func (m *CheckinRequest) XXX_Size() int {
	return xxx_messageInfo_CheckinRequest.Size(m)
}
func (m *CheckinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckinRequest proto.InternalMessageInfo

func (m *CheckinRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

// 0x02
type CheckinResponse struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckinResponse) Reset()         { *m = CheckinResponse{} }
func (m *CheckinResponse) String() string { return proto.CompactTextString(m) }
func (*CheckinResponse) ProtoMessage()    {}
func (*CheckinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0895f35a7d2a8f3, []int{1}
}

func (m *CheckinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckinResponse.Unmarshal(m, b)
}
func (m *CheckinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckinResponse.Marshal(b, m, deterministic)
}
func (m *CheckinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckinResponse.Merge(m, src)
}
func (m *CheckinResponse) XXX_Size() int {
	return xxx_messageInfo_CheckinResponse.Size(m)
}
func (m *CheckinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckinResponse proto.InternalMessageInfo

func (m *CheckinResponse) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// 0x03
type ForwardRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Mode                 string   `protobuf:"bytes,2,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`
	SourceAddr           string   `protobuf:"bytes,4,opt,name=SourceAddr,proto3" json:"SourceAddr,omitempty"`
	SourceBridge         string   `protobuf:"bytes,5,opt,name=SourceBridge,proto3" json:"SourceBridge,omitempty"`
	SourceDhcp           bool     `protobuf:"varint,6,opt,name=SourceDhcp,proto3" json:"SourceDhcp,omitempty"`
	SourceRoutes         []string `protobuf:"bytes,7,rep,name=SourceRoutes,proto3" json:"SourceRoutes,omitempty"`
	Target               string   `protobuf:"bytes,8,opt,name=Target,proto3" json:"Target,omitempty"`
	TargetAddr           string   `protobuf:"bytes,9,opt,name=TargetAddr,proto3" json:"TargetAddr,omitempty"`
	TargetBridge         string   `protobuf:"bytes,10,opt,name=TargetBridge,proto3" json:"TargetBridge,omitempty"`
	TargetRoutes         []string `protobuf:"bytes,11,rep,name=TargetRoutes,proto3" json:"TargetRoutes,omitempty"`
	TargetForwardAddr    string   `protobuf:"bytes,12,opt,name=TargetForwardAddr,proto3" json:"TargetForwardAddr,omitempty"`
	TargetCommand        []string `protobuf:"bytes,13,rep,name=TargetCommand,proto3" json:"TargetCommand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardRequest) Reset()         { *m = ForwardRequest{} }
func (m *ForwardRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardRequest) ProtoMessage()    {}
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0895f35a7d2a8f3, []int{2}
}

func (m *ForwardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardRequest.Unmarshal(m, b)
}
func (m *ForwardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardRequest.Marshal(b, m, deterministic)
}
func (m *ForwardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardRequest.Merge(m, src)
}
func (m *ForwardRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardRequest.Size(m)
}
func (m *ForwardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardRequest proto.InternalMessageInfo

func (m *ForwardRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ForwardRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *ForwardRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ForwardRequest) GetSourceAddr() string {
	if m != nil {
		return m.SourceAddr
	}
	return ""
}

func (m *ForwardRequest) GetSourceBridge() string {
	if m != nil {
		return m.SourceBridge
	}
	return ""
}

func (m *ForwardRequest) GetSourceDhcp() bool {
	if m != nil {
		return m.SourceDhcp
	}
	return false
}

func (m *ForwardRequest) GetSourceRoutes() []string {
	if m != nil {
		return m.SourceRoutes
	}
	return nil
}

func (m *ForwardRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ForwardRequest) GetTargetAddr() string {
	if m != nil {
		return m.TargetAddr
	}
	return ""
}

func (m *ForwardRequest) GetTargetBridge() string {
	if m != nil {
		return m.TargetBridge
	}
	return ""
}

func (m *ForwardRequest) GetTargetRoutes() []string {
	if m != nil {
		return m.TargetRoutes
	}
	return nil
}

func (m *ForwardRequest) GetTargetForwardAddr() string {
	if m != nil {
		return m.TargetForwardAddr
	}
	return ""
}

func (m *ForwardRequest) GetTargetCommand() []string {
	if m != nil {
		return m.TargetCommand
	}
	return nil
}

// 0x04
type ForwardResponse struct {
	Id                     string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Success                bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	Source                 string   `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`
	SourceAddr             string   `protobuf:"bytes,4,opt,name=SourceAddr,proto3" json:"SourceAddr,omitempty"`
	SourceRoutesDiscovered []string `protobuf:"bytes,5,rep,name=SourceRoutesDiscovered,proto3" json:"SourceRoutesDiscovered,omitempty"`
	Target                 string   `protobuf:"bytes,6,opt,name=Target,proto3" json:"Target,omitempty"`
	TargetAddr             string   `protobuf:"bytes,7,opt,name=TargetAddr,proto3" json:"TargetAddr,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ForwardResponse) Reset()         { *m = ForwardResponse{} }
func (m *ForwardResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardResponse) ProtoMessage()    {}
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0895f35a7d2a8f3, []int{3}
}

func (m *ForwardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardResponse.Unmarshal(m, b)
}
func (m *ForwardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardResponse.Marshal(b, m, deterministic)
}
func (m *ForwardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardResponse.Merge(m, src)
}
func (m *ForwardResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardResponse.Size(m)
}
func (m *ForwardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardResponse proto.InternalMessageInfo

func (m *ForwardResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ForwardResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ForwardResponse) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ForwardResponse) GetSourceAddr() string {
	if m != nil {
		return m.SourceAddr
	}
	return ""
}

func (m *ForwardResponse) GetSourceRoutesDiscovered() []string {
	if m != nil {
		return m.SourceRoutesDiscovered
	}
	return nil
}

func (m *ForwardResponse) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ForwardResponse) GetTargetAddr() string {
	if m != nil {
		return m.TargetAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckinRequest)(nil), "internal.CheckinRequest")
	proto.RegisterType((*CheckinResponse)(nil), "internal.CheckinResponse")
	proto.RegisterType((*ForwardRequest)(nil), "internal.ForwardRequest")
	proto.RegisterType((*ForwardResponse)(nil), "internal.ForwardResponse")
}

func init() { proto.RegisterFile("internal/natter.proto", fileDescriptor_b0895f35a7d2a8f3) }

var fileDescriptor_b0895f35a7d2a8f3 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0x54, 0xfa, 0x93, 0xa6, 0xfb, 0xf5, 0x47, 0x9f, 0x25, 0x2a, 0x9f, 0x50, 0x15, 0x81, 0xd4,
	0x03, 0x82, 0x03, 0x12, 0x77, 0x68, 0x85, 0xd4, 0x03, 0x97, 0x94, 0x17, 0x08, 0xf1, 0xaa, 0x8d,
	0xa0, 0x71, 0xb1, 0x1d, 0x78, 0x25, 0xde, 0x8b, 0x17, 0x41, 0xf1, 0x3a, 0x8d, 0x5b, 0x04, 0x07,
	0x6e, 0x3b, 0xb3, 0x9b, 0x99, 0x91, 0x27, 0x70, 0x92, 0x17, 0x06, 0x55, 0x91, 0xbe, 0x5c, 0x15,
	0xa9, 0x31, 0xa8, 0x2e, 0x77, 0x4a, 0x1a, 0xc9, 0xa2, 0x9a, 0x8e, 0x67, 0x30, 0x9a, 0x6f, 0x30,
	0x7b, 0xce, 0x8b, 0x04, 0x5f, 0x4b, 0xd4, 0x86, 0x4d, 0x20, 0x5c, 0xc9, 0x52, 0x65, 0xc8, 0x83,
	0x69, 0x30, 0xeb, 0x27, 0x0e, 0xc5, 0xe7, 0x30, 0xde, 0x5f, 0xea, 0x9d, 0x2c, 0x34, 0x32, 0x06,
	0x9d, 0x5b, 0x21, 0x94, 0x3b, 0xb4, 0x73, 0xfc, 0xd1, 0x86, 0xd1, 0xbd, 0x54, 0xef, 0xa9, 0x12,
	0xb5, 0xe2, 0x08, 0x5a, 0x4b, 0xe1, 0x8e, 0x5a, 0x4b, 0x51, 0x7d, 0xf6, 0x20, 0x05, 0xf2, 0x16,
	0x7d, 0x56, 0xcd, 0x9e, 0x6b, 0xdb, 0x77, 0x65, 0xa7, 0x00, 0x34, 0x59, 0xa3, 0x8e, 0xdd, 0x79,
	0x0c, 0x8b, 0x61, 0x40, 0xe8, 0x4e, 0xe5, 0x62, 0x8d, 0xbc, 0x6b, 0x2f, 0x0e, 0xb8, 0x46, 0x63,
	0xb1, 0xc9, 0x76, 0x3c, 0x9c, 0x06, 0xb3, 0x28, 0xf1, 0x98, 0x46, 0x23, 0x91, 0xa5, 0x41, 0xcd,
	0x7b, 0xd3, 0x76, 0xa3, 0x41, 0x5c, 0x95, 0xef, 0x31, 0x55, 0x6b, 0x34, 0x3c, 0xa2, 0x7c, 0x84,
	0x2a, 0x6d, 0x9a, 0x6c, 0xbe, 0x3e, 0xe5, 0x6b, 0x98, 0x4a, 0x9b, 0x90, 0xcb, 0x07, 0x94, 0xcf,
	0xe7, 0x9a, 0x1b, 0xe7, 0xff, 0x8f, 0xfc, 0x7d, 0x8e, 0x5d, 0xc0, 0x7f, 0xc2, 0xee, 0x6d, 0xad,
	0xdd, 0xc0, 0x8a, 0x7d, 0x5f, 0xb0, 0x33, 0x18, 0x12, 0x39, 0x97, 0xdb, 0x6d, 0x5a, 0x08, 0x3e,
	0xb4, 0x92, 0x87, 0x64, 0xfc, 0x19, 0xc0, 0x78, 0x5f, 0x95, 0xab, 0xf4, 0xb8, 0x2b, 0x0e, 0xbd,
	0x55, 0x99, 0x65, 0xa8, 0xb5, 0xad, 0x2b, 0x4a, 0x6a, 0xf8, 0xe7, 0xc6, 0x6e, 0x60, 0xe2, 0xbf,
	0xec, 0x22, 0xd7, 0x99, 0x7c, 0x43, 0x85, 0x82, 0x77, 0x6d, 0xc8, 0x1f, 0xb6, 0x5e, 0x03, 0xe1,
	0x2f, 0x0d, 0xf4, 0x8e, 0x1b, 0x78, 0x0a, 0xed, 0x2f, 0x7f, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff,
	0x35, 0xe8, 0xe9, 0xe7, 0x0b, 0x03, 0x00, 0x00,
}
